name: restyler
version: 0.2.0.0
license: MIT

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

ghc-options: -Weverything
  -Wno-unsafe
  -Wno-missing-import-lists

dependencies:
  - base

library:
  source-dirs: src
  dependencies:
    - Glob
    - aeson
    - aeson-casing
    - ansi-terminal
    - barbies
    - bytestring
    - composition-extra
    - conduit
    - containers
    - edit-distance
    - envparse
    - errors
    - extra
    - file-embed
    - filepath
    - github
    - http-client
    - http-client-tls
    - http-conduit
    - megaparsec
    - mtl
    - optparse-applicative
    - process
    - rio
    - safe
    - semigroups
    - shakespeare
    - text
    - transformers
    - unliftio
    - unordered-containers
    - validation
    - vector
    - word-wrap
    - yaml

executables:
  restyler:
    main: main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - restyler
  restyle-path:
    main: main.hs
    source-dirs: restyle-path
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - conduit
      - envparse
      - http-conduit
      - mtl
      - restyler
      - rio
      - text
      - unliftio

tests:
  test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - QuickCheck
      - aeson
      - bytestring
      - containers
      - directory
      - github
      - hspec
      - hspec-expectations-lifted
      - http-client
      - lens
      - lens-aeson
      - mtl
      - restyler
      - rio
      - shakespeare
      - text
      - yaml
