name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          curl --location --output .hlint.yaml \
            https://raw.githubusercontent.com/pbrisbin/dotfiles/master/hlint.yaml
      - uses: freckle/stack-cache-action@v1
      - uses: freckle/stack-action@v1.1

  image:
    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.prep.outputs.image }}

    steps:
      - id: prep
        run: |
          image=restyled/restyler:$(echo "${{ github.sha }}" | head -c7)
          echo "::set-output name=image::${image}"

          if ${{ github.ref == 'refs/heads/main' }}; then
            echo "::set-output name=tags::${image},restyled/restyler:main"
          else
            echo "::set-output name=tags::${image}"
          fi

      - id: buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-image-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-image-

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            REVISION=${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          push: true
          tags: ${{ steps.prep.outputs.tags }}

      # Avoids ever-growing cache hitting limits
      - run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    needs: [build, image]

    steps:
      - uses: restyled-io/gitops-deploy-action@main
        with:
          token: ${{ secrets.GITOPS_ACCESS_TOKEN }}
          parameter-name: RestylerImage
          parameter-value: ${{ needs.image.outputs.image }}
          committer-name: Restyled Commits
          committer-email: commits@restyled.io
          repository: restyled-io/ops
          stacks: cg-app/stacks/*/*/prod/services/*.yaml

      - uses: desiderati/github-action-pushover@v1
        if: ${{ always() }}
        with:
          job-status: ${{ job.status }}
          pushover-api-token: ${{ secrets.PUSHOVER_API_TOKEN }}
          pushover-user-key: ${{ secrets.PUSHOVER_USER_KEY }}
